urls.py
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('',
    url(r'', include('youtube_search.urls')),
)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        { 'document_root': settings.MEDIA_ROOT }),
)

youtube_search/urls.py
#coding: utf-8
from django.conf.urls.defaults import *

from shortcuts import route
from youtube_search.views import search, do_search

urlpatterns = patterns('',
    route(r'^$', GET=search, POST=do_search, name='search'),
)

youtube_search/forms.py
#coding: utf-8

from django import forms

class SearchForm(forms.Form):
   full_text = forms.CharField(max_length=40, required = True, label = u'Artist: ')

youtube_search/views.py
# coding:utf-8
from xml.dom import minidom
import re
import gdata.youtube
import gdata.youtube.service

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect

from youtube_search.forms import SearchForm
from config_constants import *


def search(request):
    context = RequestContext(request, {'form': SearchForm()})

    return render_to_response('search.html', context)

def do_search(request):
    search_url = 'http://www.youtube.com/results?search_query=%s&aq=f'

    form = SearchForm(request.POST)
    if form.is_valid():
        search_term =  u'allintitle:%s cover' % form.cleaned_data['full_text']
        results = __search_videos(search_term)

        context = RequestContext(request, {'videos':results, 'form':form})
        return render_to_response('search.html', context)

    else:
        context = RequestContext(request, {'form': form})

        return render_to_response('search.html', context)

def __search_videos(search_terms):
    '''
    Return a list of id videos found with the search_terms
    '''
    yt_service = gdata.youtube.service.YouTubeService()

    # The YouTube API does not currently support HTTPS/SSL access.
    yt_service.ssl = False

    yt_service.developer_key = DEVELOPER_KEY
    yt_service.client_id = CLIENT_ID

    query = gdata.youtube.service.YouTubeVideoQuery()
    search_terms = search_terms.encode('utf-8')
    query.vq = search_terms
    query.orderby = 'viewCount'
    query.racy = 'include'

    feed = yt_service.YouTubeQuery(query)

    id_videos = []
    for entry in feed.entry:
        if entry.GetSwfUrl():
            regex_result = re.search('^.*v\/([^?]+)', entry.GetSwfUrl())
            id_videos.append({'title':entry.media.title.text.strip(), 'id':regex_result.group(1)})

    return id_videos

youtube_search/templates/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <title>YouCover</title>
        <link rel="stylesheet" href="{{MEDIA_URL}}css/main.css" type="text/css" />
        <script type="text/javascript" src="{{MEDIA_URL}}js/prototype.js"></script>
        <script type="text/javascript" src="{{MEDIA_URL}}js/scriptaculous.js"></script>

        <script src="http://www.google.com/jsapi" type="text/javascript"></script>
        <script type="text/javascript">
          google.load("swfobject", "2.1");
        </script>
        <script type="text/javascript" src="{{MEDIA_URL}}js/VideoController.js"></script>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-19162715-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
    </head>
    <body>
        <div id="header">
            <div class="mainLogoContainer">
                <img src="{{MEDIA_URL}}images/logo_medio.png" class="mainLogo"></img>
            </div>
            <div class="searchFormContainer searchForm">
                <form action="." method="post" >
                    {% csrf_token %}
                    <label for="id_full_text" class="searchFormLabel">{{ form.full_text.label }}</label>
                    {{ form.full_text }}
                    {% if form.full_text.errors %}
                        <span class="inline_warning">{{ form.full_text.errors }}</span>
                    {% endif %}
                    <input type="submit" value="Covers" class="searchFormSubmit" />
                </form>
            </div>
        </div>
        <div id="mainContainer">
            <div id="mainContent">

            </div>
        </div>
        <script type="text/javascript">
            var videoArray = [];
            {% for video in videos %}
                videoArray.push({
                    'id' : '{{ video.id }}',
                    'nome' : '{{ video.title }}',
                });
            {% endfor %}
            google.setOnLoadCallback(function() {
                vController = new VideoController();

                vController.loadVideos(videoArray, 'mainContent');
            });
        </script>
    </body>
</html>